{% set goname = "github.com/git-lfs/git-lfs" %}
{% set version = "3.7.0" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: ab173702840627feb5f8a408dd5406fa322f3eadaa69938d9226b183d5be25a6

build:
  number: 0
  script:
    - set -x                                                            # [unix]
    - cd {{ pkg_src }}
    - go generate ./commands                                            # [not (osx and arm64)]
    - GOARCH=amd64 go generate ./commands                               # [osx and arm64]
    - go build -v -ldflags "-w -s" -o $PREFIX/bin/git-lfs               # [build_platform != target_platform]
    - go install -v -ldflags "-w -s" .                                  # [build_platform == target_platform and not win]
    - go build -v -ldflags "-w -s" -o %PREFIX%\Library\bin\git-lfs.exe  # [win]
    - go-licenses save . --save_path={{ SRC_DIR }}/license_files || true
    # Clear cache to avoid excessive file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)           # [unix]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  requires:
    - git  # [not win]
  commands:
    - git-lfs --help
    - where git-lfs       # [win]
    - echo %Path%         # [win]
    - git-lfs --version
    - git lfs --version

about:
  home: https://git-lfs.github.com/
  license: MIT
  license_file:
    - {{ pkg_src }}/LICENSE.md
    - license_files/
  summary: An open source Git extension for versioning large files
  dev_url: https://github.com/git-lfs/git-lfs

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
