{% set goname = "github.com/git-lfs/git-lfs" %}
{% set version = "3.5.1" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: d682a12c0bc48d08d28834dd0d575c91d53dd6c6db63c45c2db7c3dd2fb69ea4

build:
  number: 1
  script:
    - set -x                                               # [unix]
    - "env | sort"  # [unix]
    - cd {{ pkg_src }}
    - go generate ./commands                               # [not (osx and arm64)]
    - GOARCH=amd64 go generate ./commands                  # [osx and arm64]
    - go build -v -ldflags "-w -s" -o $PREFIX/bin/git-lfs  # [build_platform != target_platform]
    - go install -v -ldflags "-w -s" .                     # [build_platform == target_platform]
    - go-licenses save . --save_path={{ SRC_DIR }}/license_files || true
    # Clear cache to avoid excessive file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - git-lfs --help
    - git-lfs --version

about:
  home: https://git-lfs.github.com/
  license: MIT
  license_file:
    - {{ pkg_src }}/LICENSE.md
    - license_files/
  summary: An open source Git extension for versioning large files
  dev_url: https://github.com/git-lfs/git-lfs

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
