# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.8.0"

package:
  name: git-lfs
  version: ${{ version }}

source:
  - url: https://github.com/git-lfs/git-lfs/archive/v${{ version }}.tar.gz
    sha256: a12ecfc17ebee002d1f6acca79442029d41cbf5e5b4ba9e02249ed96de20300f
    target_directory: github.com/git-lfs/git-lfs

build:
  number: 0
  script:
    env:
      GOFLAGS: -buildmode=pie -trimpath -ldflags=-linkmode=external -mod=vendor -modcacherw
    content:
      - ${{ 'set -x' if unix else '@echo on' }}
      - cd github.com/git-lfs/git-lfs
      - if: unix
        then:
          - env -u GOARCH go generate ./commands
      - if: win
        then:
          - cmd /C "set GOARCH=&& go generate ./commands"
      - if: unix
        then:
          - go build -v -ldflags "-w -s" -o "$PREFIX/bin/git-lfs"
      - if: win
        then:
          - go build -v -ldflags "-w -s" -o "%LIBRARY_BIN%\git-lfs.exe"
      - go-licenses save . --save_path=${{ SRC_DIR }}/license_files || true
      - if: win
        then:
          - md "%LIBRARY_PREFIX%\share\bash-completion\completions" "%LIBRARY_PREFIX%\share\fish\vendor_completions.d" "%LIBRARY_PREFIX%\share\zsh\site-functions"
          - dir t\fixtures\completions
          - copy t\fixtures\completions\git-lfs-completion.bash "%LIBRARY_PREFIX%\share\bash-completion\completions\git-lfs"
          - copy t\fixtures\completions\git-lfs-completion.fish "%LIBRARY_PREFIX%\share\fish\vendor_completions.d\git-lfs.fish"
          - copy t\fixtures\completions\git-lfs-completion.zsh  "%LIBRARY_PREFIX%\share\zsh\site-functions\_git-lfs"
        else:
          - mkdir -p "${PREFIX}/share/bash-completion/completions" "${PREFIX}/share/fish/vendor_completions.d" "${PREFIX}/share/zsh/site-functions"
          - ls t/fixtures/completions
          - cp t/fixtures/completions/git-lfs-completion.bash "${PREFIX}/share/bash-completion/completions/git-lfs"
          - cp t/fixtures/completions/git-lfs-completion.fish "${PREFIX}/share/fish/vendor_completions.d/git-lfs.fish"
          - cp t/fixtures/completions/git-lfs-completion.zsh  "${PREFIX}/share/zsh/site-functions/_git-lfs"

requirements:
  build:
    - ${{ compiler('go') }}
    - go-licenses

tests:
  - package_contents:
      bin:
        - git-lfs
  - requirements:
      run:
        - if: unix and not riscv64
          then: git
    script:
      - if: not riscv64
        then: git-lfs --help
      - if: win
        then:
          - where git-lfs
          - echo "%Path%"
      - git-lfs --version

about:
  license: MIT
  license_file:
    - github.com/git-lfs/git-lfs/LICENSE.md
    - license_files/
  summary: An open source Git extension for versioning large files
  homepage: https://git-lfs.github.com
  repository: https://github.com/git-lfs/git-lfs

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
