# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mPjjJSpC7LfOaefFVLUIO5kCcPBo7wdwFE27F+ZAOyUWM8e0xuicwPKTraV3vfih/4wewNJNsGTKKRU/NudFi/jTR8XGIhrJ9Yc+ZwwY27XG1v4jusqUcWibjB3GyR7d80bWLpAxCPWEyZDhLEg667i5lzD7QsDQSzuO925HqdIhKA/YkLkKQsiksa5jgKGJjO1TYuzcYvl4rqppKKOMg5OJwbxjSXYoFiCxOZFgx2Yt/L0U16SzvWFNBrxdJ3ERzb9SVkRxt86r1GluHWekxQVTuYKKeHwKTsrVaGRJXTBwqr+tRc7ACKMD8S2024xD4Im5YVB7HbJzraGtPEyBVIrYnphCLW60lQgoORLTILGyCLpR2iieOtD+98yreKnqffewfPEeWlEJ6M7hTXPHCCSYmSQyMx9xL9+XRqzwItk1IIp0m+kONgWjy/1qyVy+qxfrW5kdHsAITBq3BGSalxMPVjkAkKYqiImrhjJ7z5N8FtgUKlkZSKzeeSiU6KHCY/EMZ+LDNHYfFMk7DSWkgQ/iVIyOtJCJTNSeUXI0/7r18CL6SdBhAuUtz9X62+4X6bWQEyH0V5ow/6gPQhagI/5hNV3MfFyDGscPazKaAvC23X86R8IkD9HwnIli4ZDO2sjKs6oSV9zMNq1rfPsLCoNE+wQkvQErgIWP4CEESmo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
